# Generated by Django 6.0.5 on 2026-06-15 10:59

import django.db.models.deletion
import payments.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0003_alter_policysubscription_status_subscriptiondocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(default=payments.models.generate_reference, editable=False, max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('payment_type', models.CharField(choices=[('NEW_SUBSCRIPTION', 'New Subscription'), ('RENEWAL', 'Renewal')], max_length=30)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], default='PENDING', max_length=20)),
                ('gateway_reference', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('gateway_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_transactions', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='subscriptions.policysubscription')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallbackLog',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_reference', models.CharField(db_index=True, max_length=255)),
                ('raw_payload', models.JSONField()),
                ('response_code', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('FLAGGED', 'Flagged')], db_index=True, max_length=20)),
                ('is_duplicate', models.BooleanField(db_index=True, default=False)),
                ('is_amount_mismatch', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callback_logs', to='payments.transaction')),
            ],
            options={
                'verbose_name': 'callback log',
                'verbose_name_plural': 'callback logs',
                'db_table': 'transaction_callback_logs',
                'ordering': ['-created_at'],
                'unique_together': {('transaction_reference', 'response_code', 'status')},
            },
        ),
    ]
