# Generated by Django 6.0.5 on 2026-10-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='access_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='authorization_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='callbacklog',
            name='gateway',
            field=models.CharField(choices=[('PAYSTACK', 'Paystack')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='gateway',
            field=models.CharField(choices=[('PAYSTACK', 'Paystack')], max_length=20),
        ),
    ]
