# Generated by Django 6.0.5 on 2026-06-30 06:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='callbacklog',
            name='gateway',
            field=models.CharField(choices=[('INTERSWITCH', 'Interswitch'), ('NOMBA', 'Nomba')], db_index=True, default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='gateway',
            field=models.CharField(choices=[('INTERSWITCH', 'Interswitch'), ('NOMBA', 'Nomba')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
