# Generated by Django 6.0.5 on 2026-08-02 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_partial_unique_pending_renewal'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transaction',
            name='unique_pending_renewal_per_subscription',
        ),
    ]
