# Generated by Django 6.0.5 on 2026-06-30 17:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('api_key', models.CharField(editable=False, max_length=64, unique=True)),
                ('partner_type', models.CharField(choices=[('provider', 'Insurance Provider'), ('distributor', 'Distribution Partner')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DistributorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.OneToOneField(limit_choices_to={'partner_type': 'distributor'}, on_delete=django.db.models.deletion.CASCADE, related_name='distributor_profile', to='core.partner')),
            ],
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('secret', models.CharField(editable=False, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='core.partner')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceWebhookEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('payment.successful', 'Payment Successful'), ('charge.failed', 'Charge Failed (Dunning)')], max_length=50)),
                ('url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_account', models.ForeignKey(limit_choices_to={'role': 'service_account'}, on_delete=django.db.models.deletion.CASCADE, related_name='service_webhooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('service_account', 'event')},
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('subscription.created', 'Subscription Created'), ('subscription.cancelled', 'Subscription Cancelled'), ('subscription.updated', 'Subscription Updated'), ('claim.submitted', 'Claim Submitted'), ('claim.status_updated', 'Claim Status Updated'), ('kyc.submitted', 'KYC Submitted'), ('kyc.approved', 'KYC Approved'), ('kyc.rejected', 'KYC Rejected')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.webhook')),
            ],
            options={
                'unique_together': {('webhook', 'event')},
            },
        ),
    ]
