# Generated by Django 6.0.5 on 2026-10-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhook',
            name='secret_hash',
        ),
        migrations.AddField(
            model_name='webhook',
            name='secret_encrypted',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AlterField(
            model_name='servicewebhookendpoint',
            name='event',
            field=models.CharField(choices=[('claim.submitted', 'Claim submitted'), ('claim.ai_check_requested', 'All documents uploaded; AI check needed'), ('claim.ai_checked', 'AI check result stored'), ('claim.flagged', 'Claim flagged for staff review'), ('claim.forwarded', 'Claim forwarded to provider'), ('provider.claim_decision', 'Provider made a decision'), ('claim.approved', 'Claim approved'), ('claim.rejected', 'Claim rejected'), ('payment.initiated', 'Claim payout started'), ('payment.completed', 'Claim payout succeeded'), ('payment.failed', 'Claim payout failed'), ('receipt.generated', 'Settlement receipt generated'), ('claim.parties_notified', 'Customer and provider informed'), ('payment.successful', 'Payment successful'), ('charge.failed', 'Charge failed (dunning)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='event',
            field=models.CharField(choices=[('claim.submitted', 'Claim submitted'), ('claim.forwarded', 'Claim forwarded to provider'), ('claim.approved', 'Claim approved'), ('claim.rejected', 'Claim rejected'), ('payment.completed', 'Claim payout succeeded'), ('claim.status_updated', 'Claim status updated (deprecated)'), ('kyc.submitted', 'KYC submitted'), ('kyc.approved', 'KYC approved'), ('kyc.rejected', 'KYC rejected'), ('subscription.created', 'Subscription created'), ('subscription.cancelled', 'Subscription cancelled'), ('subscription.updated', 'Subscription updated')], max_length=50),
        ),
    ]
