# Generated by Django 6.0.5 on 2026-07-02 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('core', '0002_seed_insurance_categories'),
    ]

    operations = [
    ]
