# Generated by Django 6.0.5 on 2026-05-15 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_webhookevent_created_at_alter_webhookevent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='partner_type',
            field=models.CharField(choices=[('provider', 'Insurance Provider'), ('distributor', 'Distribution Partner')], default='provider', max_length=20),
            preserve_default=False,
        ),
    ]
