# Generated by Django 6.0.5 on 2026-10-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_webhook_secret_hash_webhook_secret_encrypted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributorprofile',
            name='settlement_bank_account',
        ),
        migrations.RemoveField(
            model_name='distributorprofile',
            name='settlement_bank_code',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='nomba_account_id',
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='settlement_bank_account',
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='settlement_bank_code',
        ),
        migrations.AddField(
            model_name='partner',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='partner',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
