# Generated by Django 6.0.5 on 2026-05-23 12:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_partner_partner_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='commission_rate',
        ),
        migrations.CreateModel(
            name='DistributorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.OneToOneField(limit_choices_to={'partner_type': 'distributor'}, on_delete=django.db.models.deletion.CASCADE, related_name='distributor_profile', to='core.partner')),
            ],
        ),
    ]
