# Generated by Django 6.0.5 on 2026-10-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_distributorprofile_settlement_bank_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributorprofile',
            name='settlement_account_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='distributorprofile',
            name='settlement_bank_account',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='distributorprofile',
            name='settlement_bank_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='settlement_account_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='settlement_bank_account',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='settlement_bank_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
