# Generated by Django 6.0.5 on 2026-07-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_merge_0001_initial_0002_seed_insurance_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='nomba_account_id',
            field=models.CharField(blank=True, default=None, help_text="Nomba sub-account ID for payout settlement. Leave blank if this partner doesn't have one — they'll default to Interswitch checkout.", max_length=100, null=True, unique=True),
        ),
    ]
