# Generated by Django 6.0.5 on 2026-06-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_partner_commission_rate_distributorprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookevent',
            name='event',
            field=models.CharField(choices=[('subscription.created', 'Subscription Created'), ('subscription.cancelled', 'Subscription Cancelled'), ('subscription.updated', 'Subscription Updated'), ('claim.submitted', 'Claim Submitted'), ('claim.status_updated', 'Claim Status Updated'), ('kyc.submitted', 'KYC Submitted'), ('kyc.approved', 'KYC Approved'), ('kyc.rejected', 'KYC Rejected')], max_length=50),
        ),
    ]
