# Generated by Django 6.0.5 on 2026-06-30 08:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_webhookevent_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceWebhookEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('payment.successful', 'Payment Successful'), ('charge.failed', 'Charge Failed (Dunning)')], max_length=50)),
                ('url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_account', models.ForeignKey(limit_choices_to={'role': 'service_account'}, on_delete=django.db.models.deletion.CASCADE, related_name='service_webhooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('service_account', 'event')},
            },
        ),
    ]
