# Generated by Django 6.0.5 on 2026-05-16 00:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_partner_partner_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('health', 'Health'), ('motor', 'Motor'), ('property', 'Property'), ('life', 'Life'), ('travel', 'Travel'), ('business', 'Business'), ('agriculture', 'Agriculture')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Insurance Categories',
            },
        ),
        migrations.CreateModel(
            name='InsurancePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('coverage_level', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], db_index=True, max_length=20)),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('premium', models.DecimalField(db_index=True, decimal_places=2, max_digits=20)),
                ('duration_months', models.IntegerField()),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='plans.insurancecategory')),
                ('provider', models.ForeignKey(limit_choices_to={'partner_type': 'provider'}, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='core.partner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DistributorProviderAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('distributor', models.ForeignKey(limit_choices_to={'partner_type': 'distributor'}, on_delete=django.db.models.deletion.CASCADE, related_name='provider_access', to='core.partner')),
                ('provider', models.ForeignKey(limit_choices_to={'partner_type': 'provider'}, on_delete=django.db.models.deletion.CASCADE, related_name='distributor_access', to='core.partner')),
            ],
            options={
                'unique_together': {('distributor', 'provider')},
            },
        ),
    ]
