# Generated by Django 6.0.7 on 2026-07-18 12:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('health', 'Health'), ('motor', 'Motor'), ('property', 'Property'), ('life', 'Life'), ('travel', 'Travel'), ('business', 'Business'), ('agriculture', 'Agriculture')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Insurance Categories',
            },
        ),
        migrations.CreateModel(
            name='InsurancePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('coverage_level', models.CharField(choices=[('third_party', 'Third Party Only'), ('tp_fire_theft', 'Third Party, Fire & Theft'), ('comprehensive', 'Comprehensive'), ('standard', 'Standard')], db_index=True, max_length=20)),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('premium', models.DecimalField(db_index=True, decimal_places=2, max_digits=20)),
                ('duration_months', models.IntegerField()),
                ('description', models.TextField()),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public (Request Required)'), ('shared', 'Shared')], db_index=True, default='private', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='plans.insurancecategory')),
                ('provider', models.ForeignKey(limit_choices_to={'partner_type': 'provider'}, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='core.partner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DistributorAccessGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('provider', 'Provider-Level'), ('plan', 'Plan-Level')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revoked', 'Revoked'), ('withdrawn', 'Withdrawn')], db_index=True, default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('distributor', models.ForeignKey(limit_choices_to={'partner_type': 'distributor'}, on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='core.partner')),
                ('provider', models.ForeignKey(limit_choices_to={'partner_type': 'provider'}, on_delete=django.db.models.deletion.CASCADE, related_name='granted_distributor_access', to='core.partner')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, help_text='Null for provider-level grants; set for plan-level grants.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='plans.insuranceplan')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('scope', 'provider')), fields=('distributor', 'provider'), name='unique_provider_level_grant'), models.UniqueConstraint(condition=models.Q(('scope', 'plan')), fields=('distributor', 'plan'), name='unique_plan_level_grant')],
            },
        ),
    ]
