# Generated by Django 6.0.5 on 2026-10-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceplan',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private (only my own customers)'), ('public', 'Public (distributors can request access)')], db_index=True, default='private', max_length=20),
        ),
    ]
