# Generated by Django 6.0.5 on 2026-05-31 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceplan',
            name='coverage_level',
            field=models.CharField(choices=[('third_party', 'Third Party Only'), ('tp_fire_theft', 'Third Party, Fire & Theft'), ('comprehensive', 'Comprehensive'), ('standard', 'Standard')], db_index=True, max_length=20),
        ),
    ]
