# Generated by Django 6.0.5 on 2026-06-03 10:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_customerprofile_address_and_more'),
        ('core', '0004_remove_partner_commission_rate_distributorprofile'),
        ('subscriptions', '0003_alter_policysubscription_status_subscriptiondocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim_reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('claim_type', models.CharField(choices=[('motor_accident', 'Motor Accident'), ('motor_theft', 'Motor Theft'), ('travel_medical', 'Travel Medical Emergency'), ('travel_baggage', 'Travel Lost/Damaged Baggage'), ('travel_cancellation', 'Travel Flight Cancellation')], max_length=50)),
                ('incident_date', models.DateField()),
                ('incident_description', models.TextField()),
                ('claimed_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('more_info_required', 'More Information Required'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('theeinsurance_review_note', models.TextField(blank=True)),
                ('provider_review_note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='accounts.customerprofile')),
                ('provider', models.ForeignKey(limit_choices_to={'partner_type': 'provider'}, on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='core.partner')),
                ('reviewed_by_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_reviewed_claims', to='accounts.partneradmin')),
                ('reviewed_by_theeinsurance', models.ForeignKey(blank=True, limit_choices_to={'role': 'super_admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theeinsurance_reviewed_claims', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='subscriptions.policysubscription')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('claim_form', 'Completed Claim Form'), ('police_report', 'Police Report'), ('drivers_licence', "Driver's Licence"), ('damage_photos', 'Damage Photographs'), ('repair_estimate', 'Repair Estimate from Garage'), ('vehicle_particulars', 'Vehicle Particulars'), ('medical_report', 'Medical Report'), ('hospital_bills', 'Hospital Bills and Receipts'), ('property_irregularity_report', 'Property Irregularity Report'), ('flight_documents', 'Flight Tickets and Boarding Pass'), ('travel_insurance_certificate', 'Travel Insurance Certificate'), ('other', 'Other Supporting Document')], max_length=50)),
                ('file', models.FileField(upload_to='claims/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='claims.claim')),
            ],
        ),
    ]
