# Generated by Django 6.0.5 on 2026-06-30 16:31

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimdocument',
            name='file',
            field=models.FileField(storage=core.storage.KYCDocumentStorage(), upload_to='claims/documents/'),
        ),
    ]
