# Generated by Django 6.0.5 on 2026-10-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_claim_ai_result_claim_parties_notified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='forwarded_at',
            field=models.DateTimeField(blank=True, help_text='First time the claim cleared the AI/staff gate. Providers only see claims where this is set.', null=True),
        ),
        migrations.AddField(
            model_name='claimpayment',
            name='account_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='claimpayment',
            name='account_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='claimpayment',
            name='bank_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
