# Generated by Django 6.0.7 on 2026-07-18 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='core.partner'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerkyc',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to='accounts.customerprofile'),
        ),
        migrations.AddField(
            model_name='partneradmin',
            name='invited_by',
            field=models.ForeignKey(blank=True, help_text='The partner_admin who invited this team member.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members_invited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partneradmin',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='core.partner'),
        ),
        migrations.AddField(
            model_name='partneradmin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_admin_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partnerkyc',
            name='partner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to='core.partner'),
        ),
        migrations.AddField(
            model_name='staffloginevent',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_trail', to='accounts.staff'),
        ),
        migrations.AddField(
            model_name='staff',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The Super Admin who provisioned this account.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_created', to='accounts.staff'),
        ),
        migrations.AddField(
            model_name='staff',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_deactivated', to='accounts.staff'),
        ),
        migrations.AddField(
            model_name='serviceaccountcredential',
            name='staff',
            field=models.OneToOneField(limit_choices_to={'role': 'service_account'}, on_delete=django.db.models.deletion.CASCADE, related_name='service_credential', to='accounts.staff'),
        ),
        migrations.AlterUniqueTogether(
            name='customerprofile',
            unique_together={('user', 'partner')},
        ),
    ]
