# Generated by Django 6.0.5 on 2026-06-30 08:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customerprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('service_account', 'Service Account'), ('partner_admin', 'Partner Admin'), ('customer', 'Customer')], max_length=20),
        ),
        migrations.CreateModel(
            name='ServiceAccountCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('client_id', models.CharField(editable=False, max_length=64, unique=True)),
                ('client_secret_hash', models.CharField(editable=False, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'service_account'}, on_delete=django.db.models.deletion.CASCADE, related_name='service_credential', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
