# Generated by Django 6.0.5 on 2026-06-30 16:31

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_role_serviceaccountcredential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerkyc',
            name='id_document',
            field=models.FileField(storage=core.storage.KYCDocumentStorage(), upload_to='kyc/customers/id/'),
        ),
        migrations.AlterField(
            model_name='customerkyc',
            name='selfie',
            field=models.FileField(blank=True, storage=core.storage.KYCDocumentStorage(), upload_to='kyc/customers/selfie/'),
        ),
        migrations.AlterField(
            model_name='partnerkyc',
            name='cac_certificate',
            field=models.FileField(storage=core.storage.KYCDocumentStorage(), upload_to='kyc/partners/cac/'),
        ),
        migrations.AlterField(
            model_name='partnerkyc',
            name='naicom_licence_doc',
            field=models.FileField(blank=True, storage=core.storage.KYCDocumentStorage(), upload_to='kyc/partners/naicom/'),
        ),
        migrations.AlterField(
            model_name='partnerkyc',
            name='proof_of_address',
            field=models.FileField(storage=core.storage.KYCDocumentStorage(), upload_to='kyc/partners/address/'),
        ),
    ]
