"""
Django settings for theeinsurance project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from decouple import config  # type: ignore
import dotenv
import dj_database_url

dotenv.load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', cast=bool, default=False)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',

    # third party apps
    'rest_framework',
    'corsheaders',
    'drf_spectacular',
    'drf_spectacular_sidecar',
    'cloudinary_storage',
    'cloudinary',
    'django.contrib.staticfiles',

    # local apps
    'accounts',
    'analytics',
    'claims',
    'core',
    'payments',
    'plans',
    'subscriptions',
    'webhooks',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.PartnerScopeMiddleware',
]

ROOT_URLCONF = 'theeinsurance.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'theeinsurance.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
        "default": dj_database_url.parse(
        os.getenv("DATABASE_URL"),
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Lagos'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    "DEFAULT_THROTTLE_CLASSES": [],
    "DEFAULT_THROTTLE_RATES": {
        "auth": "10/hour",
        "partner": "1000/hour",
    },
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler'
}

# Simple JWT configuration
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# CORS configuration
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://mock-insurance-customer-portal.vercel.app",
]

CORS_ALLOWED_HEADERS = [
    'authorization',
    'content-type',
    'x-partner-key',
]

CORS_ALLOW_CREDENTIALS = True

AUTH_USER_MODEL = "accounts.CustomUser"

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

CLOUDINARY_STORAGE = {
    "CLOUD_NAME": os.getenv("CLOUDINARY_CLOUD_NAME"),
    "API_KEY": os.getenv("CLOUDINARY_API_KEY"),
    "API_SECRET": os.getenv("CLOUDINARY_API_SECRET"),
}

DEFAULT_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"

# CACHE CONFIGURATION
# Dev: LocMemCache (default, no setup needed)
# Prod: swap to Redis by changing the BACKEND and adding LOCATION

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "theeinsurance-throttle-cache",
    }
    # PRODUCTION
    # "default": {
    #     "BACKEND": "django.core.cache.backends.redis.RedisCache",
    #     "LOCATION": config("REDIS_URL"),
    # }
}

# Interswitch
INTERSWITCH_BASE_URL = "https://sandbox.interswitchng.com"  # test
INTERSWITCH_CLIENT_ID = config("INTERSWITCH_CLIENT_ID")
INTERSWITCH_CLIENT_SECRET = config("INTERSWITCH_CLIENT_SECRET")
INTERSWITCH_MERCHANT_CODE = config("INTERSWITCH_MERCHANT_CODE")
INTERSWITCH_PAYABLE_CODE = config("INTERSWITCH_PAYABLE_CODE")
INTERSWITCH_REDIRECT_URL = config("INTERSWITCH_REDIRECT_URL")

# Nomba
NOMBA_BASE_URL        = "https://api.nomba.com/v1"
NOMBA_CLIENT_ID       = config("NOMBA_CLIENT_ID")
NOMBA_CLIENT_SECRET   = config("NOMBA_CLIENT_SECRET")
NOMBA_ACCOUNT_ID      = config("NOMBA_ACCOUNT_ID")
NOMBA_SUB_ACCOUNT_ID  = config("NOMBA_SUB_ACCOUNT_ID")
NOMBA_CALLBACK_URL    = config("NOMBA_CALLBACK_URL")

# Payment webhook
N8N_WEBHOOK_PAYMENT_URL = config("N8N_WEBHOOK_PAYMENT_URL")
N8N_WEBHOOK_DUNNING_URL = config("N8N_WEBHOOK_DUNNING_URL")

SPECTACULAR_SETTINGS = {
    'TITLE': 'TheeInsurance API',
    'DESCRIPTION': (
        'A headless, API-first insurance distribution platform. '
        'Companies integrate TheeInsurance into their products via API '
        'and offer insurance plans to their customers without building '
        'the insurance layer themselves.'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SWAGGER_UI_DIST': 'SIDECAR',
    'SWAGGER_UI_FAVICON_HREF': 'SIDECAR',
    'REDOC_DIST': 'SIDECAR',
    "SECURITY": [{"jwtAuth": []}],
    "SECURITY_DEFINITIONS": {
        "jwtAuth": {
            "type": "http",
            "scheme": "bearer",
            "bearerFormat": "JWT",
        }
    },
    "OPERATION_ID_NAMING_STRATEGY": "operation_id",
    "SCHEMA_PATH_PREFIX": r"/api/v[0-9]",
    "COMPONENT_SPLIT_REQUEST": True,
    "ENUM_NAME_OVERRIDES": {
        "ClaimStatusEnum": "claims.models.Claim.STATUS_CHOICES",
        "SubscriptionStatusEnum": "subscriptions.models.PolicySubscription.STATUS_CHOICES",
        "PlanCoverageLevelEnum": "plans.models.InsurancePlan.COVERAGE_LEVELS",
        "InsuranceCategoryEnum": "plans.models.InsuranceCategory.CATEGORY_CHOICES",
        "SubscriptionDocumentTypeChoicesEnum": "subscriptions.models.SubscriptionDocument.DOCUMENT_TYPE_CHOICES",
        "CallbackLogStatusEnum": "payments.models.CallbackLog.Status",
        "KYCReviewStatusEnum": "accounts.models.CustomerKYC.STATUS_CHOICES",  # covers both CustomerKYC and PartnerKYC
        "CustomerKYCTypeEnum": "accounts.models.CustomerKYC.ID_TYPE_CHOICES",
    },
}

STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Legacy alias — required because django-cloudinary-storage's collectstatic
# override reads STATICFILES_STORAGE directly instead of STORAGES["staticfiles"]
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

WHITENOISE_MANIFEST_STRICT = False
