# Generated by Django 6.0.5 on 2026-05-16 09:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0003_partner_partner_type'),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicySubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], db_index=True, default='pending', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=20)),
                ('provider_payout', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('distributor_commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('payment_reference', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('payment_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='accounts.customerprofile')),
                ('distributor', models.ForeignKey(blank=True, limit_choices_to={'partner_type': 'distributor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributor_subscriptions', to='core.partner')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='plans.insuranceplan')),
                ('provider', models.ForeignKey(limit_choices_to={'partner_type': 'provider'}, on_delete=django.db.models.deletion.CASCADE, related_name='provider_subscriptions', to='core.partner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
