# Generated by Django 6.0.7 on 2026-07-18 12:15

import core.storage
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicySubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('grace_period', 'Grace Period'), ('lapsed', 'Lapsed'), ('pending_payment', 'Pending Payment'), ('pending_document', 'Pending Document')], db_index=True, default='pending_document', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=20)),
                ('provider_payout', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('distributor_commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('payment_reference', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('payment_verified', models.BooleanField(default=False)),
                ('auto_charge_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='accounts.customerprofile')),
                ('distributor', models.ForeignKey(blank=True, limit_choices_to={'partner_type': 'distributor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributor_subscriptions', to='core.partner')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='plans.insuranceplan')),
                ('provider', models.ForeignKey(limit_choices_to={'partner_type': 'provider'}, on_delete=django.db.models.deletion.CASCADE, related_name='provider_subscriptions', to='core.partner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NombaTokenStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_key', models.CharField(max_length=255)),
                ('card_type', models.CharField(blank=True, max_length=50)),
                ('card_pan', models.CharField(blank=True, max_length=50)),
                ('customer_consented_to_auto_charge', models.BooleanField(default=False)),
                ('consent_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('nomba_order_reference', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nomba_token', to='subscriptions.policysubscription')),
            ],
            options={
                'verbose_name': 'Nomba Token Store',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('vehicle_license', 'Vehicle License'), ('proof_of_ownership', 'Proof of Ownership'), ('vehicle_registration', 'Vehicle Registration'), ('inspection_report', 'Inspection Report'), ('vehicle_photos', 'Vehicle Photographs'), ('theft_declaration', 'Theft Declaration'), ('passport', 'International Passport'), ('flight_tickets', 'Flight Tickets'), ('travel_itinerary', 'Travel Itinerary'), ('insurance_certificate', 'Insurance Certificate'), ('other', 'Other')], max_length=50)),
                ('file', models.FileField(storage=core.storage.KYCDocumentStorage(), upload_to='subscriptions/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='subscriptions.policysubscription')),
            ],
            options={
                'unique_together': {('subscription', 'document_type')},
            },
        ),
    ]
