# Generated by Django 6.0.5 on 2026-10-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policysubscription',
            name='auto_charge_enabled',
        ),
        migrations.AddField(
            model_name='policysubscription',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='NombaTokenStore',
        ),
    ]
