# Generated by Django 6.0.5 on 2026-05-31 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policysubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('pending_payment', 'Pending Payment'), ('pending_document', 'Pending Document')], db_index=True, default='pending', max_length=20),
        ),
    ]
