# Generated by Django 6.0.5 on 2026-07-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('core', '0004_partner_nomba_account_id'),
        ('plans', '0001_initial'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='policysubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending_document', 'pending_payment'])), fields=('customer', 'plan'), name='unique_pending_subscription_per_customer_plan'),
        ),
    ]
