# Generated by Django 6.0.5 on 2026-05-31 13:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_policysubscription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policysubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('pending_payment', 'Pending Payment'), ('pending_document', 'Pending Document')], db_index=True, default='pending_document', max_length=20),
        ),
        migrations.CreateModel(
            name='SubscriptionDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('vehicle_license', 'Vehicle License'), ('proof_of_ownership', 'Proof of Ownership'), ('vehicle_registration', 'Vehicle Registration'), ('inspection_report', 'Inspection Report'), ('vehicle_photos', 'Vehicle Photographs'), ('theft_declaration', 'Theft Declaration'), ('passport', 'International Passport'), ('flight_tickets', 'Flight Tickets'), ('travel_itinerary', 'Travel Itinerary'), ('insurance_certificate', 'Insurance Certificate'), ('other', 'Other')], max_length=50)),
                ('file', models.FileField(upload_to='subscriptions/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='subscriptions.policysubscription')),
            ],
            options={
                'unique_together': {('subscription', 'document_type')},
            },
        ),
    ]
