# Generated by Django 6.0.5 on 2026-06-30 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_policysubscription_status_subscriptiondocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='policysubscription',
            name='auto_charge_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='policysubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('grace_period', 'Grace Period'), ('lapsed', 'Lapsed'), ('pending_payment', 'Pending Payment'), ('pending_document', 'Pending Document')], db_index=True, default='pending_document', max_length=20),
        ),
        migrations.CreateModel(
            name='NombaTokenStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_key', models.CharField(max_length=255)),
                ('card_type', models.CharField(blank=True, max_length=50)),
                ('card_pan', models.CharField(blank=True, max_length=50)),
                ('customer_consented_to_auto_charge', models.BooleanField(default=False)),
                ('consent_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('nomba_order_reference', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nomba_token', to='subscriptions.policysubscription')),
            ],
            options={
                'verbose_name': 'Nomba Token Store',
            },
        ),
    ]
