# Generated by Django 6.0.5 on 2026-06-30 16:31

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_policysubscription_auto_charge_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiondocument',
            name='file',
            field=models.FileField(storage=core.storage.KYCDocumentStorage(), upload_to='subscriptions/documents/'),
        ),
    ]
